### ISSUE TITLE
Refueling on Last Turn

### ISSUE THREAD

**Issue by katyoquinn** [anson-vandoren/skysmuggler-android#15]
When you sell all your cargo on Pertia on your last turn, the game ends, even if you have enough credits to refuel. To avoid the game ending, I sell one less than the amount of cargo I have onboard, refuel, and then sell the last one, but sometimes I habitually just sell all of them and the game ends, which kind of sucks. If there is any way to let the player choose whether to refuel or retire after selling all their cargo (provided they have enough credits to refuel), that would be great!

**Comment by anson-vandoren** [comment]
Thanks for the report, Katy! That's an interesting bug that you found, and one I haven't seen yet.

I'm currently on a business trip in China, and don't have access to my development machine right now to take a look. Sounds like it should be a pretty simple fix, though. I'll be back home in mid-May, so it's going to take some time to get it fixed for you. Sorry :/

I'll let you know once I have a chance to take a look.

**Comment by katyoquinn** [comment]
It's not a big deal! Just whenever you get the chance.

**Comment by master-elodin** [comment]
I'll take a look at this. Traveling this weekend, but I should be able to fix it on Monday.

**Comment by master-elodin** [comment]
Should be fixed now! Game will now not end until clicking 'travel' after 0 turns
