### ISSUE TITLE
Infinite play

### ISSUE THREAD

**Issue by katyoquinn** [anson-vandoren/skysmuggler-android#16]
Because I'm a data analyst/nerd, I ran some numbers on the cost of refueling versus the interest gained over 5 turns on money in the bank. I found that there's a threshold amount of credits you can put in the bank (dependent on what number turn you deposit them) that will gain enough interest to pay for refueling costs an infinite number of times. Once you reach this point, you pretty much just have to fly around and remember to withdraw money and go refuel while credits rack up in the bank, which in my opinion takes away from the point of the game. With the current interest rate, that threshold number is surprisingly low and relatively easy to reach. Lowering the interest rate for the bank would pretty easily fix this problem by increasing the number of credits needed. If you want to see all the numbers, I can send them to you.

**Comment by master-elodin** [comment]
That would be fantastic! Thanks for finding that. I never even thought about doing that.

**Comment by katyoquinn** [comment]
[Sky Smuggler Data.xlsx](https://github.com/anson-vandoren/skysmuggler-android/files/960195/Sky.Smuggler.Data.xlsx)

Here's my Excel file with all the data. If any of it needs clarification (cause it's a little messy), let me know. The "Current Rate and Refuel" sheet has all the numbers with the current rates and the minimum amount that you would need at each turn. The "Variable Rate" one lets you input different interest rates to see how it will affect the numbers. The "Interest v. Principal" one has the threshold numbers for each interest rate. The other ones after that were toying with changing the refueling cost equation, which I haven't had time to entirely hash out yet. If you've got any questions, let me know.

**Comment by anson-vandoren** [comment]
Fixed in Android version.

Waiting to release until web version is also updated.

**Comment by anson-vandoren** [comment]
Released to Android (1.18.0)

**Comment by anson-vandoren** [comment]
This is still a beta-type feature, and may need the numbers tweaked a little bit to get it to work about how I intend. It *does* still let you be lucky and get a super-high score. It also *does* still let you choose a different play-style that may lead you to never find the new features.

I didn't want an overly broad solution, so this is targeted rather specifically at Katy's discovery of "bank, fly, withdraw, buy fuel, repeat" mode of play.

The actual mechanics are left for player's discovery. You'll know it when you find it. :bowtie:

**Comment by master-elodin** [comment]
Updated on the web version too!
