### ISSUE TITLE
Sudden ending

### ISSUE THREAD

**Issue by master-elodin** [anson-vandoren/skysmuggler-android#2]
Installed properly. All mechanics seem to work. It ended rather abruptly with just a prompt to enter a high score after several turns. My score was simply my credits on hand and not my ship upgrades.

**Comment by anson-vandoren** [comment]
Not exactly sure what this one means. Does there need to be more of an explanation at the end of a game?

**Comment by master-elodin** [comment]
I think if there is a screenshot of "turns left" spot somewhere in the
instructions, that would cover it.

**Comment by anson-vandoren** [comment]
Instructions re-worked. Turns featured more prominently now. Closed
