### ISSUE TITLE
Pirates

### ISSUE THREAD

**Issue by katyoquinn** [anson-vandoren/skysmuggler-android#4]
You might look into varying the number of credits pirates take during a raid. It's always half. As a player, I would prefer it to be at least somewhat less predictable.

**Comment by anson-vandoren** [comment]
Thanks for the input. It's a good idea! It shouldn't be too difficult to implement. Are you playing on the Android version, or web? Web version updates may take a little longer as I'll need to get @master-elodin to take a look at it.

**Comment by katyoquinn** [comment]
On the web. Sadly, I don't have an Android device to play on.

**Comment by master-elodin** [comment]
Okay, it's now a randomized amount.

**Comment by master-elodin** [comment]
Right, Android version. I thought about it, didn't close it, forgot about it, closed it.

**Comment by anson-vandoren** [comment]
Updated to a weighted random number on both versions
