### ISSUE TITLE
Refueling Station

### ISSUE THREAD

**Issue by anson-vandoren** [anson-vandoren/skysmuggler-android#6]
Many of the ideas we've been kicking around would be more meaningful if the game weren't limited to 20 turns. Bribes, ship add-ons, bank usage, etc. seem a little worthless unless you have enough turns left to make use of them, and by the time you can afford them, the game is almost over.

### I propose adding a "Refueling Station" to the planet Pertia, with the following characteristics:

1. You can buy more fuel for your ship that extends the amount of turns you have left.
2. Each time you purchase fuel, the price rises (think non-renewable-resource-based fuel).
3. The game would effectively end when the cost of more turns outweighed your expected profit increase from using those turns.

#### Benefits:

- Supports other features (bribes, secret cargo compartments, ???) in the future by giving more chance to use them (extends "end game")
- Adds some fun complexity on its own by allowing you to effectively determine when it's more profitable to just retire than to continue.

#### Downsides:

- High score list would be completely upset by having more turns. This would balance out relatively quickly.
- Breaks continuity with the "original" game (that's not even available online anymore :( )
- Increases complexity and leads to longer games (may be a downside if you like the short, defined length of a single game)

## Discuss.

@katyoquinn @SoriTru not sure if you're subscribed to this list, so tagging you so hopefully you see.

**Comment by master-elodin** [comment]
I think the high score list is currently mostly "Trevor" anyway, so that
should be okay. And maybe we can still keep a "classic" option too? It
should be fairly easy for the web version. Not sure about android, though.

**Comment by anson-vandoren** [comment]
Yeah, it would be easy to do, but I'd have to re-work the Firebase backend for scores

**Comment by master-elodin** [comment]
Good point. We would need "all-time", "classic", and "weekly".

**Comment by master-elodin** [comment]
Should the number of turns that get added be reduced each time? In addition to the cost going up.

**Comment by anson-vandoren** [comment]
I think either/or, but not both. I'm thinking +5 turns per purchase, but haven't really thought much about the cost yet.

**Comment by SoriTru** [comment]
I think just the purchase price going up would work better

**Comment by anson-vandoren** [comment]
Running through some numbers, this is what I'm currently thinking:

- Each refuel gives an additional 5 turns
- Base Price = 50,000
- Each additional refuel (N) adds (BasePrice) * N^3

If you don't feel like doing the math, that works out to:

|Total Turns|Number of Refuels|Cost for Refuel|Total Cost|
|:---:|:---:|:---:|:---:|
|20|0|50,000 |50,000|
|25|1|100,000|150,000|
|30|2|450,000|600,000|
|35|3|1,400,000|2,000,000|
|40|4|3,250,000|5,250,000|
|45|5|6,300,000|11,550,000|
|50|6|10,850,000|22,400,000|
|55|7|17,200,000|39,600,000|
|60|8|25,650,000|65,250,000|

## Thoughts?

**Comment by master-elodin** [comment]
Sounds good. I'll try that out

**Comment by SoriTru** [comment]
That looks pretty good. And as far as the high score list goes, I think y'all should reset it when you release the game anyway.

**Comment by anson-vandoren** [comment]
I've got a save of the current high scores. That's good enough for now if we want to go back to it later for the Classic Mode. For now, just keep all the Firebase code as-is.

I've got an Android build ready to deploy with the Fuel Depot whenever you're ready, @master-elodin

**Comment by master-elodin** [comment]
Web version is ready to go

**Comment by master-elodin** [comment]
web version deployed

**Comment by anson-vandoren** [comment]
Android version deployed
