### ISSUE TITLE
Cargo info bug

### ISSUE THREAD

**Issue by SoriTru** [anson-vandoren/skysmuggler-android#7]
If the screen turns on and off in the middle of a game the cargo info shows up incorrectly for the rest of the game. It still functions properly, but does not always show the correct type of cargo in the hold. 
Reproduced by buying something on a planet, turning the screen off, turning it back on, traveling, and selling the cargo. After it is sold, it still shows that it's there.

**Comment by master-elodin** [comment]
For Android?

**Comment by anson-vandoren** [comment]
Yeah, Android. I'll take a look

**Comment by anson-vandoren** [comment]
Fixed. Bug found near the point in the code where I had a "TODO: Stop abusing popBackStack(); it has feelings too."

**Comment by SoriTru** [comment]
Nice
