### ISSUE TITLE
High score including turns

### ISSUE THREAD

**Issue by SoriTru** [anson-vandoren/skysmuggler-android#9]
Would be interesting if the high score list included number of turns

**Comment by SoriTru** [comment]
Also, I think commas on the high score list would be nice, especially if they're going to get this big.

**Comment by anson-vandoren** [comment]
This is relatively easy on the Android version, but not sure how/if you can make space on the web score list.

**Comment by master-elodin** [comment]
I'll take a look as soon as I can.

**Comment by master-elodin** [comment]
Added on web

**Comment by anson-vandoren** [comment]
Added to Android
